#!/usr/bin/env python

#    Copyright (C) 2011 Aaron Lindsay <aaron@aclindsay.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
from client import start, stop

def main():
    if len(sys.argv) < 2:
        usage(sys.argv)
    command = sys.argv[1]

    if command == "start":
        start()
    elif command == "stop":
        stop()
    else:
        usage(sys.argv)

def usage(argv):
    print """Usage: %s {start | stop}""" % (argv[0])
    exit(1)

if __name__ == "__main__":
    main()
